
[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "lumache"
authors = [{name = "Sergio A. Mora Pardo", email = "sergiomora823@gmail.com"}]
dynamic = ["version", "description"]